---
abstract: 'Translate a C source to an AST'
author:
  - 'Jean-Damien Durand <jeandamiendurand@free.fr>'
build_requires:
  C::Scan: 0
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  List::Util: 0
  Test::Differences: 0
  Test::More: 0
  Test::Trap: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MarpaX-Languages-C-AST
no_index:
  directory:
    - t
    - xt
    - examples
    - blog
provides:
  MarpaX::Languages::C::AST:
    file: lib/MarpaX/Languages/C/AST.pm
    version: 0.28
  MarpaX::Languages::C::AST::Callback:
    file: lib/MarpaX/Languages/C/AST/Callback.pm
    version: 0.28
  MarpaX::Languages::C::AST::Callback::Events:
    file: lib/MarpaX/Languages/C/AST/Callback/Events.pm
    version: 0.28
  MarpaX::Languages::C::AST::Callback::Method:
    file: lib/MarpaX/Languages/C/AST/Callback/Method.pm
    version: 0.28
  MarpaX::Languages::C::AST::Callback::Option:
    file: lib/MarpaX/Languages/C/AST/Callback/Option.pm
    version: 0.28
  MarpaX::Languages::C::AST::Grammar:
    file: lib/MarpaX/Languages/C/AST/Grammar.pm
    version: 0.28
  MarpaX::Languages::C::AST::Grammar::ISO_ANSI_C_2011:
    file: lib/MarpaX/Languages/C/AST/Grammar/ISO_ANSI_C_2011.pm
    version: 0.28
  MarpaX::Languages::C::AST::Grammar::ISO_ANSI_C_2011::Actions:
    file: lib/MarpaX/Languages/C/AST/Grammar/ISO_ANSI_C_2011/Actions.pm
    version: 0.28
  MarpaX::Languages::C::AST::Grammar::ISO_ANSI_C_2011::Scan:
    file: lib/MarpaX/Languages/C/AST/Grammar/ISO_ANSI_C_2011/Scan.pm
    version: 0.28
  MarpaX::Languages::C::AST::Impl:
    file: lib/MarpaX/Languages/C/AST/Impl.pm
    version: 0.28
  MarpaX::Languages::C::AST::Impl::Logger:
    file: lib/MarpaX/Languages/C/AST/Impl/Logger.pm
    version: 0.28
  MarpaX::Languages::C::AST::Scope:
    file: lib/MarpaX/Languages/C/AST/Scope.pm
    version: 0.28
  MarpaX::Languages::C::AST::Util:
    file: lib/MarpaX/Languages/C/AST/Util.pm
    version: 0.28
  MarpaX::Languages::C::AST::Util::Data::Find:
    file: lib/MarpaX/Languages/C/AST/Util/Data/Find.pm
    version: 0.28
  MarpaX::Languages::C::Scan:
    file: lib/MarpaX/Languages/C/Scan.pm
    version: 0.28
requires:
  Carp: 0
  Class::Struct: 0
  Data::Dumper: 0
  Exporter: 0
  File::Basename: 0
  File::Spec: 0
  File::Temp: 0
  Getopt::Long: 0
  IO::File: 0
  IO::Handle: 0
  IPC::Cmd: 0
  IPC::Run: 0
  Log::Any: 0
  Log::Any::Adapter: 0
  Log::Log4perl: 0
  Marpa::R2: 2.064000
  POSIX: 0
  Pod::Usage: 0
  Regexp::Common: 0
  SUPER: 0
  Scalar::Util: 0
  Term::ProgressBar: 0
  constant: 0
  diagnostics: 0
  parent: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=MarpaX-Languages-C-AST
  homepage: https://metacpan.org/release/MarpaX-Languages-C-AST
  repository: git://github.com/jddurand/marpax-languages-c-ast.git
version: 0.28
x_contributors:
  - 'Jeffrey Kegler <JKEGL@cpan.org>'
  - 'Jeffrey Kegler <jkegl@cpan.org>'
  - 'jddurand <jeandamiendurand@free.fr>'
