--- #YAML:1.0
name:               MarpaX-Languages-C-AST
version:            0.01
abstract:           Translate a C source to an AST
author:
    - Jean-Damien Durand <jeandamiendurand@free.fr>
license:            Artistic_2_0
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Clone:         0
    Log::Any:      0
    Marpa::R2:     2.055002
    Module::Info:  0
    Test::More:    0
requires:
    perl:  5.006
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
