---
abstract: 'Translate a C source to an AST'
author:
  - 'Jean-Damien Durand <jeandamiendurand@free.fr>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MarpaX-Languages-C-AST
no_index:
  directory:
    - t
    - xt
    - examples
provides:
  MarpaX::Languages::C::AST:
    file: lib/MarpaX/Languages/C/AST.pm
    version: 0.09
  MarpaX::Languages::C::AST::Grammar:
    file: lib/MarpaX/Languages/C/AST/Grammar.pm
    version: 0.09
  MarpaX::Languages::C::AST::Grammar::ISO_ANSI_C_2011:
    file: lib/MarpaX/Languages/C/AST/Grammar/ISO_ANSI_C_2011.pm
    version: 0.09
  MarpaX::Languages::C::AST::Impl:
    file: lib/MarpaX/Languages/C/AST/Impl.pm
    version: 0.09
  MarpaX::Languages::C::AST::Impl::Logger:
    file: lib/MarpaX/Languages/C/AST/Impl/Logger.pm
    version: 0.09
  MarpaX::Languages::C::AST::Scope:
    file: lib/MarpaX/Languages/C/AST/Scope.pm
    version: 0.09
  MarpaX::Languages::C::AST::Util:
    file: lib/MarpaX/Languages/C/AST/Util.pm
    version: 0.09
requires:
  Carp: 0
  Data::Dumper: 0
  Exporter: 0
  Log::Any: 0
  Marpa::R2: 2.056000
  Storable: 0
  constant: 0
  diagnostics: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=MarpaX-Languages-C-AST
  homepage: https://metacpan.org/release/MarpaX-Languages-C-AST
  repository: git://github.com/jddurand/marpax-languages-c-ast.git
version: 0.09
